### ISSUE TITLE
Github repo history re-write?

### ISSUE THREAD

**Issue by SvenDowideit** [tredoe/term#8]
Heya, we use this code in RancherOS - since 

`925a847c (Darren Shepherd 2015-02-16 16:38:49 -0700 5) import "github.com/kless/term"`

and our vendoring system has pinned a commit SHA from back then

that SHA `d57d9d2d5be197e12d9dee142d855470d83ce62f` is no longer in your tree - was this intentional?

TBH, doing this kind of thing is probably the only way to highlight important changes to vendored libraries - so its an important signaling tool :)

**Comment by tredoe** [comment]
Sorry! The username was renamed from `kless` to `tredoe`. I'm supposed that the issue is by that.

**Comment by SvenDowideit** [comment]
@tredoe wow - you only renamed the user? and that changed the commit SHA?

if so - I guess that means GitHub rebases the commit to give it the user's creation date as the first commit date - which is weird.

anyway - cool, so long as there's nothing lost - closing.
